#!/usr/bin/env bash
set -Eeuo pipefail
: "${MESER_RELEASE_DIR:?}"
: "${MESER_SECRET_DIR:?}"
: "${MESER_RUNTIME_ENV:?}"
: "${MESER_BACKUP_DESTINATION:?}"
: "${MESER_AGE_RECIPIENT:?}"
: "${MESER_BACKUP_MOUNT_ID:?}"
: "${MESER_FAILURE_DOMAIN_NOTE:?}"
"$(dirname "$0")/create-recovery-bundle.sh" "$MESER_RELEASE_DIR" "$MESER_SECRET_DIR" "$MESER_RUNTIME_ENV" "$MESER_BACKUP_DESTINATION" "$MESER_AGE_RECIPIENT" "$MESER_BACKUP_MOUNT_ID" "$MESER_FAILURE_DOMAIN_NOTE"
